---
title: Software
description: Installs preferred softwares 
privilege: TrustedInstaller
actions:

    # https://github.com/meetrevision/playbook/issues/81
  - !writeStatus: {status: 'Updating Winget'}
  - !powerShell:
    weight: 50
    runas: currentUserElevated
    wait: true
    exeDir: true
    command: '.\UPDATE-APPX.ps1'
    
  # Arc Browser
    
  - !writeStatus: {status: 'Installing Arc Browser on reboot', option: "browser-arc"}
  - !registryValue: 
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'
    value: 'Install Arc'
    type: REG_SZ
    data: 'cmd /c title Arc Browser && winget install TheBrowserCompany.Arc --silent --accept-source-agreements --accept-package-agreements'
    option: "browser-arc"

  # Zen Browser
  - !writeStatus: {status: 'Installing Zen Browser on reboot', option: "browser-zen"}
  - !registryValue: 
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'
    value: 'Install Brave'
    type: REG_SZ
    data: 'cmd /c title Zen Browser && winget install Zen-Team.Zen-Browser --silent --accept-source-agreements --accept-package-agreements'
    option: "browser-zen"

  # Google Chrome
  - !writeStatus: {status: 'Installing Google Chrome on reboot', option: "browser-chrome"}
  - !registryValue: 
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'
    value: 'Install Firefox'
    type: REG_SZ
    data: 'cmd /c title Google Chrome && winget install Google.Chrome --silent --accept-source-agreements --accept-package-agreements'
    option: "browser-chrome"

